[api-server]
port = 8001

[static-server]
port = 8002

[storage]
root = '/home/dailei/projects/www-data/storage/' # 存放courses和resume文件的根目录

  [storage.courses]
  root = 'courses/'

  [storage.resume]
  root =  'resume/'
  json = 'resume.json'
  image = 'resume.jpg'
  wechat = 'wechat.png'

[database]
host = '127.0.0.1'
port = 5432
database = 'web'
username = 'dbuser'
password = '123'
ssl = false   # 开发环境设置为false，忽略对证书的验证。正式环境应该设置为true
